language: java
install: true
jdk:
  - oraclejdk8

script:
- ./gradlew renderNoRemarksDE renderNoRemarksEN

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - "build/foundation-curriculum_de.pdf"
    - "build/foundation-curriculum_en.pdf"
  skip_cleanup: true
  draft: true
  overwrite: true
