language: java
install: true
jdk:
  - opendk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew renderNoRemarksDE renderNoRemarksEN

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - "build/template-curriculum_de.pdf"
    - "build/template-curriculum_en.pdf"
  skip_cleanup: true
  draft: true
  overwrite: true
